import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";

//Components
import Navigation from "./components/Navigation";
import HomePage from "./components/HomePage";
import Footer from "./components/Footer";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Happy Planet</title>
        <meta
          content="Generated by @rainbow-me/create-rainbowkit"
          name="description"
        />
        <link href="/favicon.ico" rel="icon" />
      </Head>

      <Navigation />
      <HomePage />
      <Footer />
    </div>
  );
};

export default Home;
